---
version: '3.8'

services:
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
      - exclude:/api/venv
      - exclude:/api/.pytest_cache
    working_dir: /api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  web:
    build: .
    ports:
      - 5173:5173
    depends_on:
      - api
    volumes:
      - .:/app
      - exclude:/app/node_modules/

volumes:
  exclude: